# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PLOT_v4.ui'
#
# Created: Fri Dec  7 10:12:21 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.setEnabled(True)
        Dialog.resize(1084, 622)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(9, 9, 1066, 604))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.mpl = MplWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setMinimumSize(QtCore.QSize(600, 600))
        self.mpl.setObjectName(_fromUtf8("mpl"))
        self.horizontalLayout_14.addWidget(self.mpl)
        self.line_7 = QtGui.QFrame(self.widget)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_14.addWidget(self.line_7)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.l_columns = QtGui.QLabel(self.widget)
        self.l_columns.setObjectName(_fromUtf8("l_columns"))
        self.verticalLayout.addWidget(self.l_columns)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.l_x = QtGui.QLabel(self.widget)
        self.l_x.setObjectName(_fromUtf8("l_x"))
        self.horizontalLayout_3.addWidget(self.l_x)
        self.spin_x = QtGui.QSpinBox(self.widget)
        self.spin_x.setMinimum(1)
        self.spin_x.setObjectName(_fromUtf8("spin_x"))
        self.horizontalLayout_3.addWidget(self.spin_x)
        self.l_y = QtGui.QLabel(self.widget)
        self.l_y.setObjectName(_fromUtf8("l_y"))
        self.horizontalLayout_3.addWidget(self.l_y)
        self.spin_y = QtGui.QSpinBox(self.widget)
        self.spin_y.setMinimum(2)
        self.spin_y.setObjectName(_fromUtf8("spin_y"))
        self.horizontalLayout_3.addWidget(self.spin_y)
        self.l_start = QtGui.QLabel(self.widget)
        self.l_start.setObjectName(_fromUtf8("l_start"))
        self.horizontalLayout_3.addWidget(self.l_start)
        self.slide_start = QtGui.QSlider(self.widget)
        self.slide_start.setMinimum(1)
        self.slide_start.setProperty("value", 10)
        self.slide_start.setOrientation(QtCore.Qt.Horizontal)
        self.slide_start.setObjectName(_fromUtf8("slide_start"))
        self.horizontalLayout_3.addWidget(self.slide_start)
        self.l_stop = QtGui.QLabel(self.widget)
        self.l_stop.setObjectName(_fromUtf8("l_stop"))
        self.horizontalLayout_3.addWidget(self.l_stop)
        self.slide_stop = QtGui.QSlider(self.widget)
        self.slide_stop.setMinimum(1)
        self.slide_stop.setProperty("value", 10)
        self.slide_stop.setOrientation(QtCore.Qt.Horizontal)
        self.slide_stop.setObjectName(_fromUtf8("slide_stop"))
        self.horizontalLayout_3.addWidget(self.slide_stop)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_3 = QtGui.QFrame(self.widget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.l_xlabel = QtGui.QLabel(self.widget)
        self.l_xlabel.setObjectName(_fromUtf8("l_xlabel"))
        self.horizontalLayout_5.addWidget(self.l_xlabel)
        self.edit_xlabel = QtGui.QLineEdit(self.widget)
        self.edit_xlabel.setObjectName(_fromUtf8("edit_xlabel"))
        self.horizontalLayout_5.addWidget(self.edit_xlabel)
        self.l_xsize = QtGui.QLabel(self.widget)
        self.l_xsize.setObjectName(_fromUtf8("l_xsize"))
        self.horizontalLayout_5.addWidget(self.l_xsize)
        self.slide_xsize = QtGui.QSlider(self.widget)
        self.slide_xsize.setMinimum(8)
        self.slide_xsize.setProperty("value", 20)
        self.slide_xsize.setOrientation(QtCore.Qt.Horizontal)
        self.slide_xsize.setObjectName(_fromUtf8("slide_xsize"))
        self.horizontalLayout_5.addWidget(self.slide_xsize)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.l_x_ticks = QtGui.QLabel(self.widget)
        self.l_x_ticks.setObjectName(_fromUtf8("l_x_ticks"))
        self.horizontalLayout_12.addWidget(self.l_x_ticks)
        self.slide_xnr = QtGui.QSlider(self.widget)
        self.slide_xnr.setMinimum(3)
        self.slide_xnr.setMaximum(20)
        self.slide_xnr.setProperty("value", 5)
        self.slide_xnr.setOrientation(QtCore.Qt.Horizontal)
        self.slide_xnr.setObjectName(_fromUtf8("slide_xnr"))
        self.horizontalLayout_12.addWidget(self.slide_xnr)
        self.l_xsizeticks = QtGui.QLabel(self.widget)
        self.l_xsizeticks.setObjectName(_fromUtf8("l_xsizeticks"))
        self.horizontalLayout_12.addWidget(self.l_xsizeticks)
        self.slide_xsizeticks = QtGui.QSlider(self.widget)
        self.slide_xsizeticks.setMinimum(8)
        self.slide_xsizeticks.setProperty("value", 18)
        self.slide_xsizeticks.setOrientation(QtCore.Qt.Horizontal)
        self.slide_xsizeticks.setObjectName(_fromUtf8("slide_xsizeticks"))
        self.horizontalLayout_12.addWidget(self.slide_xsizeticks)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.line_5 = QtGui.QFrame(self.widget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.l_ylabel = QtGui.QLabel(self.widget)
        self.l_ylabel.setObjectName(_fromUtf8("l_ylabel"))
        self.horizontalLayout_6.addWidget(self.l_ylabel)
        self.edit_ylabel = QtGui.QLineEdit(self.widget)
        self.edit_ylabel.setObjectName(_fromUtf8("edit_ylabel"))
        self.horizontalLayout_6.addWidget(self.edit_ylabel)
        self.l_ysize = QtGui.QLabel(self.widget)
        self.l_ysize.setObjectName(_fromUtf8("l_ysize"))
        self.horizontalLayout_6.addWidget(self.l_ysize)
        self.slide_ysize = QtGui.QSlider(self.widget)
        self.slide_ysize.setMinimum(8)
        self.slide_ysize.setProperty("value", 20)
        self.slide_ysize.setOrientation(QtCore.Qt.Horizontal)
        self.slide_ysize.setObjectName(_fromUtf8("slide_ysize"))
        self.horizontalLayout_6.addWidget(self.slide_ysize)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.l_y_ticks = QtGui.QLabel(self.widget)
        self.l_y_ticks.setObjectName(_fromUtf8("l_y_ticks"))
        self.horizontalLayout_13.addWidget(self.l_y_ticks)
        self.slide_ynr = QtGui.QSlider(self.widget)
        self.slide_ynr.setMinimum(3)
        self.slide_ynr.setMaximum(20)
        self.slide_ynr.setProperty("value", 5)
        self.slide_ynr.setOrientation(QtCore.Qt.Horizontal)
        self.slide_ynr.setObjectName(_fromUtf8("slide_ynr"))
        self.horizontalLayout_13.addWidget(self.slide_ynr)
        self.l_ysizeticks = QtGui.QLabel(self.widget)
        self.l_ysizeticks.setObjectName(_fromUtf8("l_ysizeticks"))
        self.horizontalLayout_13.addWidget(self.l_ysizeticks)
        self.slide_ysizeticks = QtGui.QSlider(self.widget)
        self.slide_ysizeticks.setMinimum(8)
        self.slide_ysizeticks.setProperty("value", 18)
        self.slide_ysizeticks.setOrientation(QtCore.Qt.Horizontal)
        self.slide_ysizeticks.setObjectName(_fromUtf8("slide_ysizeticks"))
        self.horizontalLayout_13.addWidget(self.slide_ysizeticks)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.l_title = QtGui.QLabel(self.widget)
        self.l_title.setObjectName(_fromUtf8("l_title"))
        self.horizontalLayout_7.addWidget(self.l_title)
        self.edit_title = QtGui.QLineEdit(self.widget)
        self.edit_title.setObjectName(_fromUtf8("edit_title"))
        self.horizontalLayout_7.addWidget(self.edit_title)
        self.l_label = QtGui.QLabel(self.widget)
        self.l_label.setObjectName(_fromUtf8("l_label"))
        self.horizontalLayout_7.addWidget(self.l_label)
        self.edit_label = QtGui.QLineEdit(self.widget)
        self.edit_label.setObjectName(_fromUtf8("edit_label"))
        self.horizontalLayout_7.addWidget(self.edit_label)
        self.l_titlesize = QtGui.QLabel(self.widget)
        self.l_titlesize.setObjectName(_fromUtf8("l_titlesize"))
        self.horizontalLayout_7.addWidget(self.l_titlesize)
        self.slide_titlesize = QtGui.QSlider(self.widget)
        self.slide_titlesize.setMinimum(8)
        self.slide_titlesize.setProperty("value", 18)
        self.slide_titlesize.setOrientation(QtCore.Qt.Horizontal)
        self.slide_titlesize.setObjectName(_fromUtf8("slide_titlesize"))
        self.horizontalLayout_7.addWidget(self.slide_titlesize)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line_4 = QtGui.QFrame(self.widget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.check_xlim = QtGui.QCheckBox(self.widget)
        self.check_xlim.setObjectName(_fromUtf8("check_xlim"))
        self.horizontalLayout_2.addWidget(self.check_xlim)
        self.l_xmin = QtGui.QLabel(self.widget)
        self.l_xmin.setObjectName(_fromUtf8("l_xmin"))
        self.horizontalLayout_2.addWidget(self.l_xmin)
        self.edit_xmin = QtGui.QLineEdit(self.widget)
        self.edit_xmin.setObjectName(_fromUtf8("edit_xmin"))
        self.horizontalLayout_2.addWidget(self.edit_xmin)
        self.l_xmax = QtGui.QLabel(self.widget)
        self.l_xmax.setObjectName(_fromUtf8("l_xmax"))
        self.horizontalLayout_2.addWidget(self.l_xmax)
        self.edit_xmax = QtGui.QLineEdit(self.widget)
        self.edit_xmax.setObjectName(_fromUtf8("edit_xmax"))
        self.horizontalLayout_2.addWidget(self.edit_xmax)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.check_ylim = QtGui.QCheckBox(self.widget)
        self.check_ylim.setObjectName(_fromUtf8("check_ylim"))
        self.horizontalLayout_11.addWidget(self.check_ylim)
        self.l_ymin = QtGui.QLabel(self.widget)
        self.l_ymin.setObjectName(_fromUtf8("l_ymin"))
        self.horizontalLayout_11.addWidget(self.l_ymin)
        self.edit_ymin = QtGui.QLineEdit(self.widget)
        self.edit_ymin.setObjectName(_fromUtf8("edit_ymin"))
        self.horizontalLayout_11.addWidget(self.edit_ymin)
        self.l_ymax = QtGui.QLabel(self.widget)
        self.l_ymax.setObjectName(_fromUtf8("l_ymax"))
        self.horizontalLayout_11.addWidget(self.l_ymax)
        self.edit_ymax = QtGui.QLineEdit(self.widget)
        self.edit_ymax.setObjectName(_fromUtf8("edit_ymax"))
        self.horizontalLayout_11.addWidget(self.edit_ymax)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.line_6 = QtGui.QFrame(self.widget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout.addWidget(self.line_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.l_divy = QtGui.QLabel(self.widget)
        self.l_divy.setObjectName(_fromUtf8("l_divy"))
        self.horizontalLayout_8.addWidget(self.l_divy)
        self.edit_divy = QtGui.QLineEdit(self.widget)
        self.edit_divy.setObjectName(_fromUtf8("edit_divy"))
        self.horizontalLayout_8.addWidget(self.edit_divy)
        self.l_multy = QtGui.QLabel(self.widget)
        self.l_multy.setObjectName(_fromUtf8("l_multy"))
        self.horizontalLayout_8.addWidget(self.l_multy)
        self.edit_multy = QtGui.QLineEdit(self.widget)
        self.edit_multy.setObjectName(_fromUtf8("edit_multy"))
        self.horizontalLayout_8.addWidget(self.edit_multy)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.l_divx = QtGui.QLabel(self.widget)
        self.l_divx.setObjectName(_fromUtf8("l_divx"))
        self.horizontalLayout_10.addWidget(self.l_divx)
        self.edit_divx = QtGui.QLineEdit(self.widget)
        self.edit_divx.setText(_fromUtf8("1"))
        self.edit_divx.setObjectName(_fromUtf8("edit_divx"))
        self.horizontalLayout_10.addWidget(self.edit_divx)
        self.l_multx = QtGui.QLabel(self.widget)
        self.l_multx.setObjectName(_fromUtf8("l_multx"))
        self.horizontalLayout_10.addWidget(self.l_multx)
        self.edit_multx = QtGui.QLineEdit(self.widget)
        self.edit_multx.setObjectName(_fromUtf8("edit_multx"))
        self.horizontalLayout_10.addWidget(self.edit_multx)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.btn_corrections = QtGui.QPushButton(self.widget)
        self.btn_corrections.setEnabled(False)
        self.btn_corrections.setObjectName(_fromUtf8("btn_corrections"))
        self.horizontalLayout_9.addWidget(self.btn_corrections)
        self.btn_empty = QtGui.QPushButton(self.widget)
        self.btn_empty.setEnabled(False)
        self.btn_empty.setObjectName(_fromUtf8("btn_empty"))
        self.horizontalLayout_9.addWidget(self.btn_empty)
        self.btn_pythonize = QtGui.QPushButton(self.widget)
        self.btn_pythonize.setObjectName(_fromUtf8("btn_pythonize"))
        self.horizontalLayout_9.addWidget(self.btn_pythonize)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.combo_module = QtGui.QComboBox(self.widget)
        self.combo_module.setEnabled(False)
        self.combo_module.setMinimumSize(QtCore.QSize(150, 0))
        self.combo_module.setObjectName(_fromUtf8("combo_module"))
        self.horizontalLayout_4.addWidget(self.combo_module)
        self.btn_module = QtGui.QPushButton(self.widget)
        self.btn_module.setEnabled(False)
        self.btn_module.setObjectName(_fromUtf8("btn_module"))
        self.horizontalLayout_4.addWidget(self.btn_module)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.check_grid = QtGui.QCheckBox(self.widget)
        self.check_grid.setObjectName(_fromUtf8("check_grid"))
        self.horizontalLayout.addWidget(self.check_grid)
        self.check_tight = QtGui.QCheckBox(self.widget)
        self.check_tight.setChecked(False)
        self.check_tight.setObjectName(_fromUtf8("check_tight"))
        self.horizontalLayout.addWidget(self.check_tight)
        self.check_label = QtGui.QCheckBox(self.widget)
        self.check_label.setChecked(False)
        self.check_label.setObjectName(_fromUtf8("check_label"))
        self.horizontalLayout.addWidget(self.check_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_14.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.l_columns.setText(QtGui.QApplication.translate("Dialog", "Columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_x.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.l_y.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.l_start.setText(QtGui.QApplication.translate("Dialog", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.l_stop.setText(QtGui.QApplication.translate("Dialog", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.l_xlabel.setText(QtGui.QApplication.translate("Dialog", "X Label", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_xlabel.setText(QtGui.QApplication.translate("Dialog", "$x \\, label$", None, QtGui.QApplication.UnicodeUTF8))
        self.l_xsize.setText(QtGui.QApplication.translate("Dialog", "X size", None, QtGui.QApplication.UnicodeUTF8))
        self.l_x_ticks.setText(QtGui.QApplication.translate("Dialog", "X Ticks Nr", None, QtGui.QApplication.UnicodeUTF8))
        self.l_xsizeticks.setText(QtGui.QApplication.translate("Dialog", "X size ticks", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ylabel.setText(QtGui.QApplication.translate("Dialog", "Y Label", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_ylabel.setText(QtGui.QApplication.translate("Dialog", "$y \\, label$", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ysize.setText(QtGui.QApplication.translate("Dialog", "Y size", None, QtGui.QApplication.UnicodeUTF8))
        self.l_y_ticks.setText(QtGui.QApplication.translate("Dialog", "Y Ticks Nr", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ysizeticks.setText(QtGui.QApplication.translate("Dialog", "Y size ticks", None, QtGui.QApplication.UnicodeUTF8))
        self.l_title.setText(QtGui.QApplication.translate("Dialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_title.setText(QtGui.QApplication.translate("Dialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.l_label.setText(QtGui.QApplication.translate("Dialog", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_label.setText(QtGui.QApplication.translate("Dialog", "$ label $", None, QtGui.QApplication.UnicodeUTF8))
        self.l_titlesize.setText(QtGui.QApplication.translate("Dialog", "title size", None, QtGui.QApplication.UnicodeUTF8))
        self.check_xlim.setText(QtGui.QApplication.translate("Dialog", "X lim ", None, QtGui.QApplication.UnicodeUTF8))
        self.l_xmin.setText(QtGui.QApplication.translate("Dialog", "X min:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_xmax.setText(QtGui.QApplication.translate("Dialog", "X max:", None, QtGui.QApplication.UnicodeUTF8))
        self.check_ylim.setText(QtGui.QApplication.translate("Dialog", "Y lim", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ymin.setText(QtGui.QApplication.translate("Dialog", "Y min:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_ymax.setText(QtGui.QApplication.translate("Dialog", "Y max:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_divy.setText(QtGui.QApplication.translate("Dialog", "Div Y.", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_divy.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.l_multy.setText(QtGui.QApplication.translate("Dialog", "Mult. Y", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_multy.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.l_divx.setText(QtGui.QApplication.translate("Dialog", "Div X.", None, QtGui.QApplication.UnicodeUTF8))
        self.l_multx.setText(QtGui.QApplication.translate("Dialog", "Mult. X", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_multx.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_corrections.setText(QtGui.QApplication.translate("Dialog", "Shape Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_empty.setText(QtGui.QApplication.translate("Dialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_pythonize.setText(QtGui.QApplication.translate("Dialog", "Pythonize", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_module.setText(QtGui.QApplication.translate("Dialog", "Apply module", None, QtGui.QApplication.UnicodeUTF8))
        self.check_grid.setText(QtGui.QApplication.translate("Dialog", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.check_tight.setText(QtGui.QApplication.translate("Dialog", "Tight", None, QtGui.QApplication.UnicodeUTF8))
        self.check_label.setText(QtGui.QApplication.translate("Dialog", "Label", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
